languageCode: en-us
baseURL: "https://lexromo.net/blog/"
title: Lex Romo
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ChaninNantasenamat
  description: "HI there!, this my website where you will find all my projects and alittle bit more about me. **."
  keywords: [Blog, cloud computing, cybersecurity]
  author: alex romo
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Lex Romo"
    icon: "be-cyber1.jpg"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome everyone! \U0001F44B"
    subtitle: "Welcome to **Lex Romo** blog, where
    you will find alittle bit more about **me**, and more information of my **projects**.
    I have a passion for everything related to technology, specially **Cloud Computing and Cybersecurity**."
    imageUrl: "be-cyber1.jpg"
    imageWidth: 170
    imageHeight: 150
    imageTitle: "Alex Romo"
    content: my name is alex romo
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "This is the website of **Chanin Nantasenamat, Ph.D.** and
    I create educational content on data science and bioinformatics.
    Some of you may know me as the **Data Professor**."

  socialIcons:
    - name: twitter
      url: "https://twitter.com/lexromoo"
    - name: linkedin
      url: "https://www.linkedin.com/"
    - name: github
      url: "https://github.com/lexromo"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 2
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 3
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

